apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
      restartPolicy: Never
  backoffLimit: 4


