apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    accelerator: nvidia-tesla-p100
  name: nginx4
spec:
  containers:
  - image: nginx
    name: nginx4
  nodeSelector: 
    accelerator: nvidia-tesla-p100
