apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "132a"
  name: "132a"
spec:
  containers:
  - image: nginx
    name: "132a"
    ports:
    - containerPort: 80
      name: liveness-port
    livenessProbe:
      httpGet:
        path: /indexz.html
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 60
      # Override pod-level terminationGracePeriodSeconds #
      terminationGracePeriodSeconds: 60
