apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "132b"
  name: "132b"
spec:
  containers:
  - image: nginx
    name: "132b"
    ports:
    - containerPort: 80
      name: liveness-port
    livenessProbe:
      httpGet:
        path: /index.html
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 30

    startupProbe:
      httpGet:
        path: /index.html
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 30
