apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cat-init-nginx
  name: cat-init-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat-init-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cat-init-nginx
        foo: bar
        project: cat
    spec:
      volumes:
      - name: workdir
        emptyDir: {}
      initContainers:
      - name: install
        image: busybox
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://info.cern.ch
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
