apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"webapp-color"},"name":"webapp-color","namespace":"default"},"spec":{"containers":[{"image":"kodekloud/webapp-color","name":"webapp","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"}}}]}}
  creationTimestamp: "2021-11-01T20:26:34Z"
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
  resourceVersion: "1396322"
  selfLink: /api/v1/namespaces/default/pods/webapp-color
  uid: 730362ad-3fac-4e13-8472-3409205ff260
spec:
  containers:
  - image: kodekloud/webapp-color
    imagePullPolicy: Always
    name: webapp
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4b9d6
      readOnly: true
    env:
      - name: APP_COLOR
        value: pink
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-4b9d6
    secret:
      defaultMode: 420
      secretName: default-token-4b9d6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-01T20:26:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-11-01T20:26:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-11-01T20:26:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-11-01T20:26:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a511bcb1e1f67516d963e80b691da31da23be6bc22cbac690aef52778377e63d
    image: kodekloud/webapp-color:latest
    imageID: docker-pullable://kodekloud/webapp-color@sha256:99c3821ea49b89c7a22d3eebab5c2e1ec651452e7675af243485034a72eb1423
    lastState: {}
    name: webapp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-11-01T20:26:43Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.145
  podIPs:
  - ip: 10.1.0.145
  qosClass: Guaranteed
  startTime: "2021-11-01T20:26:34Z"
