apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pvc-01
  name: nginx-pvc-01
spec:
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: block-pvc-01
  containers:
  - image: nginx
    name: nginx-pvc-01
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
     - mountPath: "/usr/share/nginx/html"
       name: mypd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
