apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-122
  name: nginx-122
spec:
  volumes:
  - name: foo
    secret:
      secretName: mysecret-122
  containers:
  - image: nginx
    name: nginx-122
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true 
