apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod-01
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
      - name: SECRET_USERNAME
        value: my-secret-user
      - name: SECRET_PASSWORD
        value: zippity-dippity-do
  restartPolicy: Never
