apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngin-limits
  name: ngin-limits
spec:
  containers:
  - image: nginx
    name: ngin-limits
    resources:
      requests:
        memory: "100Gi"
      limits:
        memory: "200Gi"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
