apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxenv
  name: nginxenv
spec:
  containers:
  - image: nginx
    name: nginxenv
    env:
      - name: key1
        valueFrom:
          configMapKeyRef:
            name: config.txt
            key: key1

  restartPolicy: Always
status: {}
