apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cfg-vol
  name: nginx-cfg-vol
spec:
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: cfgvolume
  containers:
  - image: nginx
    name: nginx-cfg-vol
    volumeMounts:
    - name: config-volume
      mountPath: /etc/cfg
