apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - image: busybox
    name: sec-ctx-demo
    #image: busybox
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      runAsGroup: 2000

