apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp-busy
  name: temp-busy
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600; ls
    image: busybox
    name: temp-busy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
