apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector-01
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    nodeName: nginxnode-01

