apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-server
    ports:
    - containerPort: 80
      name: nginx-port
    startupProbe:
      httpGet:
        path: /
        port: nginx-port
        scheme: HTTP
        httpHeaders:
        - name: X-Client-Identity
          value: Kubernetes-Startup-Probe
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: nginx-port
      initialDelaySeconds: 15
    livenessProbe:
      httpGet:
        path: /
        port: nginx-port
      initialDelaySeconds: 15
      periodSeconds: 30
    resources:
      limits:
        memory: "500Mi"
        cpu: "1"
      requests:
        memory: "500Mi"
        cpu: "1"       
  dnsPolicy: ClusterFirst
  # securityContext:
  #   allowPrivilegeEscalation: false
    # privileged: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # SrunAsNonRoot: true
  restartPolicy: Never
status: {}