apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubeapp
  name: kubeapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubeapp
    #env: prod
    #env in (production, qa)
  type: NodePort
status:
  loadBalancer: {}
