apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypods
  name: mypods
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date; sleep 10; done
    image: busybox
    name: mypods
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
