apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
    tier: backend
  name: labled-pod
spec:
  containers:
  - image: nginx
    name: labled-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
