apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-green
  name: deployment-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-green
    spec:
      containers:
      - image: nginx:1.21.0
        name: nginx
        resources: {}
status: {}
