apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-blue
  name: deployment-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-blue
    spec:
      containers:
      - image: nginx:1.20.0
        name: nginx
        resources: {}
status: {}
