apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-sa
  name: nginx-sa-01
spec:
  serviceAccountName: myuser
  containers:
  - image: nginx
    name: nginx-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
