apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentchallenge
  labels:
    type: local
spec:
  storageClassName: challenge
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"