apiVersion: v1
kind: Pod
metadata:
  name: storagepodlet
spec:
  containers:
  - name: nginx-with-pv
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: nginx-pv-storage
      mountPath: "/data"
  volumes:
  - name: nginx-pv-storage
    persistentVolumeClaim:
      claimName: persistentclaimchallenge